-- RLS

ALTER TABLE "Repo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Depend" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReposDepends" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Topic" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReposTopics" ENABLE ROW LEVEL SECURITY;

